### ISSUE TITLE
Wrap text

### ISSUE THREAD

**Issue by ethanyoung** [slim-template/language-slim#16]
It can be seen that in Sublime's [ruby-slim](https://github.com/slim-template/ruby-slim.tmbundle), slim code is wrapped. But in Atom code is not wrapped. Is it an issue here?

**Comment by tshedor** [comment]
@ethanyoung I believe you're looking for the [Soft Wrap](https://stackoverflow.com/a/35701155) feature. It will enable line wrapping across the editor.
