### ISSUE TITLE
image_tag has no syntax highlighting

### ISSUE THREAD

**Issue by hlambeth** [slim-template/language-slim#18]
when using = image_tag it doesn't highlight blue like other rails helpers
<img width="655" alt="screen shot 2016-02-22 at 11 27 43 pm" src="https://cloud.githubusercontent.com/assets/11952287/13242589/ece61a18-d9bb-11e5-8a0d-e99d79b36527.png">

**Comment by tshedor** [comment]
Hey @hlambeth Slim doesn't highlight Rails helpers. However, I've made a PR on the Rails repo to address this issue. I'm closing this out and would direct you to that PR for future updates.

**Comment by spotontheresa** [comment]
Hi actually wanted to use this too. Any workaround? Thanks!
