### ISSUE TITLE
Synthax color go wrong if they were an attribute before

### ISSUE THREAD

**Issue by GuillaumeLegendre** [slim-template/language-slim#19]
![capture d ecran 2016-03-01 a 19 25 25](https://cloud.githubusercontent.com/assets/561036/13437223/6492a46e-dfe3-11e5-9fd9-b699bbcd5918.jpg)

You can see on the picture than after the ' the synthax color go wrong if they were an attribute before.

This is pretty annoying because it happen on all the following of the files.

**Comment by tshedor** [comment]
@GuillaumeLegendre  Hey, this should be all patched up in v1.0. Please let me know if it's not working for you.
