### ISSUE TITLE
Syntax Coloring Incorrect for Attributes Containing ':' Character

### ISSUE THREAD

**Issue by ksylvest** [slim-template/language-slim#20]
``` slim
.foo v-model="name" v-bind:class="{...}"
```

<img width="392" alt="demo" src="https://cloud.githubusercontent.com/assets/73432/17651870/0cf76780-6224-11e6-8ffa-0feaa0fa7e69.png">

These attributes appear often when using the `vue.js` for doing class / style bindings (would expect `v-bind:class=` to appear in red).

**Comment by leonelgalan** [comment]
On the grammar there is a pattern called _interpolated-ruby_ which has the following `begin`: 

```cson
"interpolated-ruby":
  begin: "([\\w.#_-]+)(=)(?!\\s)(true|false|nil)?(\\s*\\(|\\{)?"
  captures:
      "1":
        name: "entity.other.attribute-name.event.slim"
      "2":
        name: "punctuation.separator.key-value.html"
      "3":
        name: "constant.language.slim"
```

The first match: `([\\w.#_-]+)` captures _entity.other.attribute-name.event.slim_ which would be highligted in red in theme (orange in mine, see screenshot). Simply adding the `:` to that character class does the trick, except you want to leave `-` at the end: `([\w.#_:-]+)`

![screen shot 2018-11-29 at 2 01 47 pm](https://user-images.githubusercontent.com/727774/49245097-5be83000-f3df-11e8-9547-59bc97d79cf0.png)

There are 2 other expressions that capture _entity.other.attribute-name.event.slim_. I'm a little stretched here, so I don't know if all 3 have to be modified. The others are slightly different:

1. [Line: 195](https://github.com/slim-template/language-slim/blob/v1.0.0/grammars/ruby%20slim.cson#L195): `([\\w-]+)`
2. [Line 212](https://github.com/slim-template/language-slim/blob/v1.0.0/grammars/ruby%20slim.cson#L212): `([\\w-]+)`
3. [Line 425](https://github.com/slim-template/language-slim/blob/v1.0.0/grammars/ruby%20slim.cson#L425): `([\\w.#_-]+)` **This one is the one above**

**Comment by leonelgalan** [comment]
@swrobel, thanks for reminding me about this issue. When I posted this "solution" I was trying help maintainers see a possible solution for them to fix it, but I became one, so it's up to me now.

From what's discussed on #25, for now: I'll sync the grammar with the latest from [slim-template/ruby-slim.tmbundle](https://github.com/slim-template/ruby-slim.tmbundle):

```sh
wget https://raw.githubusercontent.com/slim-template/ruby-slim.tmbundle/master/Syntaxes/Ruby%20Slim.YAML-tmLanguage
node_modules/.bin/yaml2json "Ruby Slim.YAML-tmLanguage" -p | node_modules/.bin/json2cson --2spaces > "grammars/ruby slim.cson"
```

That project has the same bug, so I'm going to submit an issue and try to get it merged, but the project hasn't had any changes in a while. Meanwhile, I'll simply add `:` to all regexes for _entity.other.attribute-name.event.slim_. I'm not sure why I said:

>  except you want to leave `-` at the end 

It appears this prevents a runtime error: "Error: empty range in char class"
