### ISSUE TITLE
Multiline Ruby with `ruby:` not highlighted correctly

### ISSUE THREAD

**Issue by itay-grudev** [slim-template/language-slim#23]
When you have a multiline inline Ruby like:

```slim
.container
  ruby:
    this_code_here( :is_not_highlighted_as_ruby )
```

The code inside the ruby block is not highlighted like Ruby but like Slim.

**Comment by tshedor** [comment]
@itay-grudev @killthekitten Hey, this should be all patched up in v1.0. Please let me know if it's not working for you.
