### ISSUE TITLE
Multi line text highlight

### ISSUE THREAD

**Issue by LeviSchuck** [slim-template/language-slim#24]
Multi line text does not highlight properly.

Taken from the slim page:
```
p
 | No items found.  Please add some inventory.
   Thank you!
```

Here, `Thank` is highlighted as if a tag token.
![image](https://user-images.githubusercontent.com/245911/28948263-281ea8bc-787a-11e7-84ef-4c9cbc4c40a6.png)

**Comment by tshedor** [comment]
@LeviSchuck Hey, this should be all patched up in v1.0. Please let me know if it's not working for you.
