### ISSUE TITLE
Looking for maintainers!

### ISSUE THREAD

**Issue by fredwu** [slim-template/language-slim#25]
Hi everyone,

Given I've been writing less Ruby these days and I haven't really been using Slim for a while. I am looking for maintainers to take over this project.

Please reply to this issue if you're interested, or get in touch with me via email: ifredwu [at] gmail [dot] com

Thanks!

Also: https://github.com/slim-template/ruby-slim.tmbundle/issues/73

**Comment by leonelgalan** [comment]
@fredwu, I've collaborated in the past (#22; very little, but still) and actively using both Ruby and Slim. I wouldn't mind helping out as a collaborator. Could you explain me the relation between https://github.com/slim-template/ruby-slim.tmbundle and this repo? I've seen the other more active and this one catching up. Have you found a maintainer for that repo? Couldn't that maintainer take care of this repo as well?

**Comment by tilsammans** [comment]
@fredwu any progress on this issue? You people waiting to take over, no trouble to add them to the repo is it? Or move it to their accounts?

**Comment by fredwu** [comment]
Thanks @tilsammans. I must've overlooked notification emails from Github... @leonelgalan are you still willing to help maintain this package? If so I'll add you to the repo.

**Comment by leonelgalan** [comment]
I am. Did you see my previous question about the relation between https://github.com/slim-template/ruby-slim.tmbundle and this repo?

**Comment by fredwu** [comment]
@leonelgalan Great! Just added you to the org. :) 

This one was initially converted from the tmbundle then the two got diverged a little and maintained separately. I guess it is now up to you all to decide what the best way forward is. :D

**Comment by swrobel** [comment]
@leonelgalan are you actively maintaining or is the call still open for maintainers?

**Comment by leonelgalan** [comment]
@swrobel, I am. At least keeping an eye on incoming issues/pull requests. I'm certainly not in a leadership role to decide if it's still open for maintainers.

**Comment by swrobel** [comment]
@leonelgalan good to hear! I assume that means just reviewing PRs, not actively working to fix issues like #20?
