### ISSUE TITLE
Comments not being greyed out.

### ISSUE THREAD

**Issue by unmultimedio** [slim-template/language-slim#26]
When comments are indented at same level, without a space from last line of code, it doesn't gets greyed out if slim has ruby code.

![slim-comment](https://user-images.githubusercontent.com/4431392/29905756-237954da-8dd6-11e7-94de-4ac5159f3723.gif)

**Comment by tshedor** [comment]
@unmultimedio Hey, this should be all patched up in v1.0. Please let me know if it's not working for you.
