### ISSUE TITLE
Multiline HTML Attributes

### ISSUE THREAD

**Issue by jclusso** [slim-template/language-slim#8]
I have this problem with multiline html attributes

![screen shot 2015-03-29 at 8 41 54 pm](https://cloud.githubusercontent.com/assets/622516/6888697/1ad29d96-d654-11e4-9b01-b9a1f29ddb3f.png)

**Comment by Signum** [comment]
Not sure if the same issue but I see a similar problem:

![634_auswahl](https://user-images.githubusercontent.com/36562/29401153-5cd792f6-8330-11e7-8084-8075f90d97c8.png)

**Comment by jclusso** [comment]
@Signum unfortunately nobody appears to care lol. I've been waiting for this for years. :(

**Comment by tshedor** [comment]
@jclusso @Signum Friends, apologies for this not being addressed earlier. I've had trouble writing this in the [tmbundle](https://github.com/slim-template/ruby-slim.tmbundle) as well. It's something at the very top of my list.

**Comment by leonelgalan** [comment]
As of yesterday, we are simply converting the tmbundle's grammar into Atom's cson. So we can concentrate into the issue, let's keep move it there: https://github.com/slim-template/ruby-slim.tmbundle/issues/76
